### PR TITLE
add miri test in CI

### PR DESCRIPTION
**Pull request by botika**
#18

### CODE REVIEW

**Comment by fereidani** [comment]
It takes too much time, I don't think my free GitHub plan is enough for this, I need to run a private VPS for this CI test. then we can merge it.

**Comment by botika** [comment]
It is not necessary, if it is public you have all the time you want.

**Comment by fereidani** [comment]
I think we got 2000 minutes per month and darwin tests are using 2x per minute.
I'm updating the project regularly and I'm always running Miri test on my system before merge.
I'm not sure that 2000 minutes will be enough as described in : https://github.com/pricing

**Comment by botika** [comment]
It is true! Github give us the copilot and not the minutes. Well, we close it to see if Microsoft releases more minutes...

**Pull request closed without merging**
