### PR TITLE
Use proper atomic orderings, cleanup codebase

### PR DESCRIPTION
**Pull request by terrarier2111**
Using proper atomic orderings should have a strong, measurable performance impact.
Also i moved a bunch of compile time size checks into KanalPtr's methods so callers don't have to verify these preconditions themselves.

### CODE REVIEW

**Comment by fereidani** [comment]
Thanks for the pull request!
I changed a lot in my latest commits, could you please update your pull request with the latest library version?
I believe that the current implementation and algorithm of the library do not require AcqRel in the areas that you changed, and it only slows down the library without solving any problems. I'm open to investigating if you are open to providing resources and examples about problems that may exist in the library that this pull request solves.

**Comment by terrarier2111** [comment]
> Thanks for the pull request! I changed a lot in my latest commits, could you please update your pull request with the latest library version? I believe that the current implementation and algorithm of the library do not require AcqRel in the areas that you changed, and it only slows down the library without solving any problems. I'm open to investigating if you are open to providing resources and examples about problems that may exist in the library that this pull request solves.

Sure, i'll update it.
I just chose AcqRel because it was easily verifyable that it is safe to use it and it is weaker than SeqCst and can (and in practive will) lead to significant performance improvements. Furthermore it is easy to choose even weaker orderings if possible once i get more familiar with the library code. Also howcome choosing a weaker ordering would "slow down the library and not solve anything" if it improves performance significantly (just to give an anecdotal example MIRI and other race condition detecting tools largely aren't even supporting SeqCst because of the exponential growth of possible executions with every additional SeqCst access.

**Comment by fereidani** [comment]
Thanks!
I wrote some benchmarking tools for the library, I'll benchmark between before and after your commit to test how your commit is affecting the performance of Kanal.
the place that worries me for performance regression is the  `let v = self.v.load(Ordering::Acquire)` and `self.v.store(UNLOCKED, Ordering::Release)` because I think with acquire thread will hold some tag about acquired atomic and I'm not sure if we need that or not.
If I recall correctly Golang is avoiding using anything but sequential consistent atomics as they ended up with some bugs with less restricted atomic operations in some hardwares. So if we end up with a very small  performance advantage I'm hesitant to merge the atomic part. but as I said I'm open to exploring the idea further.
It would be great to send the cleanup part as another PR, so we can focus on atomic parts here.

**Comment by terrarier2111** [comment]
I thought Kanal's main goal was performance and the correctness and safety of the library aren't certain now so at least IMHO we should definitely abuse weaker atomic orderings and the change from SeqCst to Acquire/Release/AcqRel is easily verifyable to be safe just from the fact that Kanal isn't even using 3 atomics (which is the minimum amount of atomics which need to be present in order for SeqCst to be necessary)
I found some soundness bugs and race conditions in your recent changes and in your KanalPtr implementation, so i think you should compare against an older commit without the new `backoff` feature. The race condition i found was with your random impl because it assumes that between an Acquire load and Release store no race condition can occour which is incorrect. You should probably use the widely used `random` library to get thread local randoms which are safe to use concurrently without synchronization.

**Comment by terrarier2111** [comment]
> Thanks! I wrote some benchmarking tools for the library, I'll benchmark between before and after your commit to test how your commit is affecting the performance of Kanal. the place that worries me for performance regression is the `let v = self.v.load(Ordering::Acquire)` and `self.v.store(UNLOCKED, Ordering::Release)` because I think with acquire thread will hold some tag about acquired atomic and I'm not sure if we need that or not. If I recall correctly Golang is avoiding using anything but sequential consistent atomics as they ended up with some bugs with less restricted atomic operations in some hardwares. So if we end up with a very small performance advantage I'm hesitant to merge the atomic part. but as I said I'm open to exploring the idea further. It would be great to send the cleanup part as another PR, so we can focus on atomic parts here.

On the acquire Thread `holding` part, i am really not sure what you mean with that, because it only changes ordering and doesn't hold a thread or anything. Also the current version that uses SeqCst already does an Acquire and Release AND on top of that does some additional work, so all that will change in the worst case is that less work will be done.

**Comment by fereidani** [comment]
Thanks for your contribution,I think it's not right to sacrifice correctness and safety for performance, also I agree that Kanal is not battle-tested yet, it is not acceptable to add more things to push boundaries in the name of that.
I'll wait for your changes, to test performance, we can decide and talk about it more after that.
with `backoff` we got about 50% improvements with MPMC for sync and 70% for async and it also performs much better with a higher number of threads, I checked the part that you are talking about and I think you are right, I'll rewrite that part later with a while loop and compare_swap, maybe relaxed is enough there too, I'm not sure.
Please just keep things organized using separate commits and PRs so we can manage the merge process more productively.

**Comment by fereidani** [comment]
It would be cool to have that safe wrapper.
Sure, I'll add you.

**Pull request merged**
